### ISSUE TITLE
hwmon for Infineon DPS 310 device driver. 

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1196]

**Comment by spinler** [comment]
The Infineon DPS310 is the new ambient sensor on the Teak fan riser card.  It is showing up in the ITC level of the cards currently scheduled for the first or second week in May.  It is replacing the BMP280 that has too near an EOL.

I have a datasheet if anyone needs it.   Also, I have a contact who can have a part reworked onto a Teak in Rochester or Austin.

It is also a pressure sensor, but we don't have a hard requirement to display altitude, only ambient temperature (as an input to fan control).  The BMP280 had an IIO subsystem driver instead of hwmon, probably because it read pressure.  We will need it to show up in hwmon, but I believe the iio-hwmon driver can bridge that if necessary.

**Comment by jk-ozlabs** [comment]
Datasheet is at http://www.infineon.com/dgdl/Infineon-DPS310-DS-v01_00-EN.pdf?fileId=5546d462576f34750157750826c42242

**Comment by shenki** [comment]
@spinler This will be i2c attached?

**Comment by spinler** [comment]
@shenki Yea, it's I2C.

**Comment by shenki** [comment]
@spinler okay. I have a driver to test once we have hardware ready. Let me know how you go with the reworked system

**Comment by shenki** [comment]
A working driver was posted here:

 http://patchwork.ozlabs.org/patch/755499/

Upstream suggested we use the IIO framework instead, so it will be reworked to use that API.

**Comment by shenki** [comment]
The iio version was posted today:

 https://patchwork.kernel.org/patch/9710865/

**Comment by bjwyman** [comment]
Isn't this done, or is it waiting on some upstream process?

**Comment by amboar** [comment]
Well, we have it in openbmc/linux dev-4.10: https://github.com/openbmc/linux/blob/dev-4.10/drivers/iio/pressure/dps310.c

Upstream were asking @shenki to implement the pressure sensor side of it, but it's probably closed for OpenBMC purposes?

**Comment by spinler** [comment]
Closing.
