### ISSUE TITLE
mboxd: Create the toc in virtual pnor

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1439]
Create a virtual toc (table of contents) in memory by copying the toc file that the squashfs image contains.
When copying files to memory, use mmap.

**Comment by geissonator** [comment]
Notes from task review:
TOC Is at beginning of PNOR, host comes down and reads first 2 pages (open window), we need to hand back TOC.  This task hard codes the open window with first 2 pages as input to call special function created here to generate and return TOC because TOC in PNOR may not be accurate.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4001 msg: handle partition table read request
Resolves #1439 mboxd: Create the toc in virtual pnor
