### ISSUE TITLE
[System] Host from running is going into off state after rebooting BMC

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc#1572]
With power restore policy set to RESTORE_LAST_STATE, Host is going into off state after rebooting BMC with HOST in running state. BMC Reboot was triggered using /sbin/reboot on BMC. 

Journal logs:
[Journal logs for power restore issue.txt](https://github.com/openbmc/openbmc/files/983513/Journal.logs.for.power.restore.issue.txt)

BMC FW info:
```
- [x] VERSION_ID : v1.99.5-15-gc4c2bed
- [x] PNOR VERSION: witherspoon_20170501n.pnor
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410
```

**Comment by williamspatrick** [comment]
@geissonator is reset/reload considered supported function at this point?  I thought we are still working on that?

**Comment by geissonator** [comment]
Well, we have 2 different things here.  If you issue a bmc reset while the OS is up and running, we should leave the OS up and running and get our chassis and host states to represent that.  That function is all in and working, except for it doesn't work on witherspoon due to #1322 .  This same test will work fine on a barreleye.

Now, if you have the OS up and running and were to pull A/C with a policy of RESTORE_LAST_STATE then that should cause the firmware to automatically boot the system.  That code is not in place though because we're awaiting the persistent storage design to be complete.

**Comment by rahulmah** [comment]
This feature is available in Witherspoon. So closing the issue.
