### ISSUE TITLE
bootcount is not changing for failures in Hostboot

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#187]
147 is a system with a lot of problems.  Seems like there is no working memory dimms.  It turns out that it constantly restarts the ipl.  Boot Count is suppose to determine that we are only trying 3 times before we but the system in a failed state.  Because of the lack of stopping the system event log gets filled with 7xreboot.  A system trying to reboot over night can easily create over 400 event logs.

**Comment by anoo1** [comment]
How do you recreate, is it a continuous power on/off? Want to verify this pull request addresses it:
https://github.com/openbmc/phosphor-host-ipmid/pull/70

**Comment by anoo1** [comment]
I just remembered, it's with the pnor image that doesn't support the old dimms. Will try it out.

**Comment by anoo1** [comment]
Boot count fixed with https://github.com/openbmc/phosphor-host-ipmid/pull/70
The system would still try to power back on after the watchdog expires (since hostboot fails to start up, a stop watchdog request is not sent). This would be a different discussion to see if hostboot expects the BMC to stop the watchdog if they fail to start.
