### ISSUE TITLE
ipk formst issue

### ISSUE THREAD

**Issue by yongli3** [openbmc/openbmc#1897]
In order to decrease the image size, I switched the package from rpm to ipk, but the bitbake failed.
It seems that the wsgiref-2.7-manifest.inc uses incorrect naming format. "_" is illegal for ipk package

**Comment by williamspatrick** [comment]
Packages installed on the machine are not in rpm format in bitbake, even if rpm was selected, so changing the package format is not going to save any space. That sounds like a package that comes from upstream Yocto, so we would need them to make any changes to support ipk instead of rpm. This isn't something we are interested in investing the time required to fix.
