### ISSUE TITLE
Software Version ID Enhancements

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2291]
<cde:info> SW400255 </cde:info>

**Comment by stewart-ibm** [comment]
https://gerrit.openbmc-project.xyz/#/c/6758/ at least partially addresses this as you can calculate the image id.

**Comment by anoo1** [comment]
**STATUS**
9/28 - Discussion on having the REST upload return the id are in progress, after the change Stewart mentions above is completed.

**Comment by zahrens** [comment]
The software version id is a hash calculated over the version string of the image.

Some requested enhancements have been the ability for the user to be able to calculate
externally that id so that there's no need to enumerate the dbus object to find it after uploading an
image.

Also calculate the hash over perhaps the whole tar file so that the version id is different even if
the version string is the same, like in the case of dirty git commits.

**Comment by gtmills** [comment]
The bug internal to IBM was closed. There is still a related issue here: https://github.com/openbmc/openbmc/issues/2290
