### ISSUE TITLE
[xCAT] Reboot of BMC will no longer reflect correct functional PNOR IDs

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2533]
<cde:info> SW405946 </cde:info>

**Comment by anoo1** [comment]
If you perform a PNOR update at power on, followed by a BMC reboot, the new PNOR level will take effect even though there was not a host reboot.

Need a way for the code update code to know that the host was on prior to the BMC reboot so that it doesn't point to the new version until the host is rebooted.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7732> updatesymlinks: Only run on host power on
Resolves  #2533 [xCAT] Reboot of BMC will no longer reflect correct functional PNOR IDs
