### ISSUE TITLE
During link local address delete network daemon restarted

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2575]
<cde:info> SW407462 </cde:info>

**Comment by amboar** [comment]
This issue has been tagged as `ibm-internal` because it references IBM-internal tags, commits, machines or issues. This is a public issue tracker and is for the benefit of the community. If any of the details are not publicly accessible then the issue should be filed elsewhere, or reworded to reflect the relevant publicly accessible details.

**Comment by rfrandse** [comment]
network configuration will not work consistently via REST interface. It should work with in band - ipmitool interface. This will impact network configuration functions.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7863> Create netlink socket outside from rtnetlink server
Resolves  #2575 During link local address delete network daemon restarted
