### ISSUE TITLE
Pegas1.0 - STC:OP910:Witherspoon: yl13uf:Unable IPL after Update BMC/PNOR form 1742C to 1742E

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2604]
<cde:info> SW408042 </cde:info>

**Comment by amboar** [comment]
This issue has been tagged as `ibm-internal` because it references IBM-internal firmware bundles, tags, commits, machines or issues. This is a public issue tracker and is for the benefit of the community. If any of the details are not publicly accessible then the issue should be filed elsewhere, or reworded to reflect the relevant publicly accessible details.
