### ISSUE TITLE
Mapper Error-  Error starting event loop: Connection timed out

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2656]
<cde:info> SW408588 </cde:info>

**Comment by tomjoseph83** [comment]
This issue is opened to increase the priority of the mapper process to -5. The mapper is the dbus service discovery manager which is used pervasively by openbmc applications. During stress tests it was observed that mapper is loaded and fails leading to a chain of other failures. The plan is to set a higher priority for the mapper process.The observation with the changes was that mapper responded faster leading to an overall better BMC performance.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7997> Set the nice value of mapper process to -5
Resolves  #2656 Mapper Error-  Error starting event loop: Connection timed out

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7997> Set the nice value of mapper process to -5
Resolves  #2656 Mapper Error-  Error starting event loop: Connection timed out
