### ISSUE TITLE
Default PowerSuppyRedundancy to be Enabled

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2665]
<cde:info> SW408962 </cde:info>

**Comment by geissonator** [comment]
The power management subsystem on openpower platforms uses this IPMI sensor, PowerSuppyRedundancy, to determine it's policy when it detects a power supply has failed.  The default for this currently is set to "Disabled".  This means if a power supply fails, the OCC will not take corrective actions like throttling the GPU's or processors to maintain n level power settings.

It has been determined that the better default here is to have this "Enabled" so that the OCC does do these things by default when a power supply fails.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8030> Change default of PowerSupplyRedundancy to enabled
Resolves  #2665 Default PowerSuppyRedundancy to be Enabled

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8043> Add sensor entry for power supply redundancy enabled.
Resolves  #2665 Default PowerSuppyRedundancy to be Enabled

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8043> Add sensor entry for power supply redundancy enabled.
Resolves  #2665 Default PowerSuppyRedundancy to be Enabled
