### ISSUE TITLE
Remove old power supply inventory objects

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2726]
<cde:info> SW410875 </cde:info>

**Comment by spinler** [comment]
On Witherspoon, the power supply inventory object names had to change from power_supply to powersupply in a previous driver.  Unfortunately, the power_supply inventory objects are persisted and will stay in the inventory until a factory reset is done.

Some inventory-manager rules should be able to be set up to delete that old path so that users won't see 4 power supplies in their inventory.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8578> Witherspoon: Destroy invalid inventory on startup
Resolves  #2726 Remove old power supply inventory objects
