### ISSUE TITLE
OpenBMC GUI -> There should be appropriate and user friendly warning message has to display for "Sensors" Sub menu -> "FILTER BY SEVERITY" option

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc#2748]
![sensors sub menu user friendly warning message has to display](https://user-images.githubusercontent.com/29222610/34413345-d1b387a6-ec08-11e7-930e-40e795a5d117.png)

**Comment by samahaba** [comment]
In "Server health" main menu -> "Sensors" sub menu under "FILTER BY SEVERITY" option, if there is no "Critical" or "Warning" event logs not in a list, then it will be a good have appropriate user friendly warning message display.

**Comment by karlvochatzer** [comment]
Similar to #2747, I'd say that @iftekharuli should consider that the Critical is disabled when there are no sensor data results that match "critical" levels, that would then never display a null set like is shown above. Otherwise, yes a string ought to be displayed below the Sensors header that says something like "There are no sensors in a Critical state."

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8914> Adding user friendly warning message in sensor page
fixes  #2748 OpenBMC GUI -> There should be appropriate and user friendly warning message has to display for "Sensors" Sub menu -> "FILTER BY SEVERITY" option
