### ISSUE TITLE
GUI: User should be able to select "Critical" and "Warning" Sensors (and not be redirected to "All")

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc#2750]
![sensors - warning option](https://user-images.githubusercontent.com/29222610/34486467-1e844bd8-eff6-11e7-830d-8ae5e0e16ffd.png)

**Comment by samahaba** [comment]
Steps to reproduce the problem
--------------------------------------

1. Go to "Server health" -> "Sensors"
2. Click on "All"
3. Click on "Critical"
4. Click on "Warning" and now observer that  there is no display shown which are belongs to "Warning" even though warning shown under "All" option

**Comment by iftekharuli** [comment]
@samahaba this is how it is designed. If you are selecting "critical", it will show critical issues. If you select "warning", it will show warning issues.  

In the scenario above, you are selecting critical and then you are selecting warning. This means you are selecting "critical"**and** "warning". That is why "All" is being selected. Since All means critical and warning. 

I think what is being confusing here is- these items are not OR. These acts more like AND. 
In other word, think of these are checkboxes. Not radio buttons. 

[Karl](https://github.com/karlvochatzer) can probably explian more.

**Comment by gtmills** [comment]
The user should be able to select "Critical" and "Warning" without being redirected to "All"

**Comment by gtmills** [comment]
Go to "Server health" then try to select "Critical" and "Warning"

**Comment by iftekharuli** [comment]
The way we designed this, we automatically select all when all the types are met. So, what do you suggest the third type would be? Can we categorize them as Normal? So that it is Critical, warning and Normal?

**Comment by gtmills** [comment]
Yes, there would be 3 categories "Critical", "Warning", and "Normal". Not sure if "Normal" is the correct term and I don't know if the user would ever select "Normal".. Having "Normal" sensors displayed only when "All" is selected might be enough.

**Comment by gtmills** [comment]
I am okay with adding a 3rd category for these "Normal" sensors. I am also okay with just allowing the user to select "Critical" and "Warning".

**Comment by iftekharuli** [comment]
just allowing the user to select "Critical" and "Warning" breaks the design convention in the project, I will add normal button

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9628> Adding new button 'Normal' in sensors page
Fixes  #2750 GUI: User should be able to select "Critical" and "Warning" Sensors (and not be redirected to "All")

**Comment by iftekharuli** [comment]
Normal button has been added per discussion. This is how the GUI looks now. 

![screen shot 2018-04-10 at 10 46 16 am](https://user-images.githubusercontent.com/4976631/38567691-74ad58d0-3cac-11e8-93e4-b1f3c88b7fe7.png)
