### ISSUE TITLE
Improvements in Mapper Performance

### ISSUE THREAD

**Issue by tomjoseph83** [openbmc/openbmc#2860]

**Comment by amboar** [comment]
@tomjoseph83 can you provide some information here about what the problem is and how you plan to address it? How do we know that we have a performance issue? Has anyone quantified it? What strategies do we have for improving it? When can we close this issue (i.e. what's our threshold for having "fixed" the performance issue)?

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/153
