### ISSUE TITLE
Power cap range invalid on MRW systems

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2909]
<cde:info> SW417036 </cde:info>

**Comment by spinler** [comment]
Premature bridging.  Closing.

**Comment by gtmills** [comment]
For Witherspoon, the power cap range should be 500 to 3050 Watts, these values come from the MRW.
This is broke on master.

https://github.com/openbmc/openbmc/commit/a62ad5c1856b90752a49a0a0115399671806b83e broke this.

a62ad5c1856b90752a49a0a0115399671806b83e appended -native to native setting recipes to
follow bitbake naming conventions but left out this directory.
phosphor-settings-read-settings-mrw/ should have been renamed to phosphor-settings-read-settings-mrw-native/ since
phosphor-settings-read-settings-mrw.bb was renamed to phosphor-settings-read-settings-mrw-native.bb
