### ISSUE TITLE
IPMI:- Should support change of password for default user

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#2943]
Currently  user can change the password through REST but out of band IPMI doesn't support for change of password.
I feel we should provide change of password for default user.

I understand that we are coming up with full user management but for the **security perspective** we should not allow always with the default password.

**Comment by ratagupt** [comment]
As I explained above we would be coming up with user management feature in near future but meanwhile we should be having a way to change the default password.
We can achieve the same for a short term as follows.
1) Implement the set user password command for IPMI.
       This command will change the root password of ths system by having a dbus call(setPassword) to the phosphor-user manager.
       It will also store the password in the text format for the IPMI as IPMI requires the password in the text format.
       Now we have two scenario
              1)  Either we keep the password as it is and save it in the file(unencrypted format).
              2)  Keep the encrypted password(symmetric encryption).
       I am favoring option 2 as I have read somewhere keeping the password in raw text format is also a security vulnerability.
             So for the symmetric key encryption we need some shared secret which can be used for encryption as well as decryption.
             My suggestion is can we use the same key which comes as part of code update but it can be changed at any successive code updates.
            So we can ask the build team to provide another key which should not be changed.
Please feel free to provide other proposals.

**Comment by tomjoseph83** [comment]
I would prefer that root password(unix user account) is detached from the IPMI user account management. The root password is stored as one-way hash but the IPMI password can be decrypted back to plain text(even in the case of encryption), this is considered as a vulnerability. So it is always better to separate these two user accounts.

IPMI has the Set Password command to change the password. This can be used to change the IPMI password. Additionally a dbus interface can be provided which would allow the IPMI password(default account) to be changed via REST. This would ensure that customer can change the IPMI password via a secure way.

Since the ssh is disabled in customer scenarios, it might be a good intermediate option to keep the password as plain text, till a full fledged user account management in place. If the secret key is on the flash and the password is encrypted, it will make the password obscure, but leave room for vulnerability.

**Comment by ratagupt** [comment]
I am having other opinion of having two user management 1) for IPMI and other for rest of other apps. I think that is good topic for design..

**Comment by bradbishop** [comment]
@vmauery @nasamuffin for your awareness....

**Comment by ratagupt** [comment]
@vmauery @nasamuffin what is your opinion having same password for ipmi and rest of the clients v/s different password for IPMI and rest of the clients.
    I am having couple of points.
        1) I think in @rthomaiy  proposal we are having same password for both the clients(rest v/s IPMI).
        2) how is other stack implementation?
My point was we should not change the behavior for the user.

**Comment by nasamuffin** [comment]
This came up in the IPMI maintainer call last night.  The thought was that Intel is working on a more robust account management system, and if IBM needs this for an internal release, IBM should apply it only downstream as a patch.  Tom pitched this as throwaway code - and if it's meant to be replaced anyway, and only wanted by IBM, there's no reason to put it upstream, especially for something with potential security implementations like this.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10034> Changes for taking updated pasword from file.
Resolves  #2943 IPMI:- Should support change of password for default user
