### ISSUE TITLE
Pegas1.0 - power9: SOL console too slow to interrupt petitboot (performance)

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2958]
<cde:info> SW401765 </cde:info>

**Comment by rfrandse** [comment]
Description of problem:
After recent firmware updates, PXE was accidentally left disabled on ibm-p9w-02 in our Beaker lab.  Using the IPMI SOL console, I tried to interrupt petitboot and add PXE back in as a boot option, but the text output to the SOL console was so slow that petitboot had already timed out and booted from disk by the time I even saw the petitboot menu.  (It was so slow, in fact, the OS was already fully booted and I was able to ssh into the full OS while the petitboot menu was just being printed to the SOL console.)

Fortunately the ssh console on port 2200 was much faster and I was able to get in and fix ibm-p9w-02.  But since the SOL console is the standard, we need it to be faster than what appears to be 9600 baud output.
