### ISSUE TITLE
Networkd:- Allow gateway to be configure which is not in the same subnet of IP

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#2987]
In current implementation if default gateway is not in the same subnet of configured IP..then systemd-networkd doesn't allow to configure..
With this defect we should allow the default gateway to be configured in any subnet.

**Comment by amboar** [comment]
What/who is driving this requirement?

**Comment by mdmillerii** [comment]
In addition to @amboar comment, assigning the gateway to be on something other than a directly reachable route does not make any sense.

**Comment by ratagupt** [comment]
@amboar : No body asked for this..I thought it should have been there as I could have set any gateway ip in normal linux box.

I had done some googling and figured it out that configuration should not stop it so I opened up this one.
Please refer the below link..
https://learningnetwork.cisco.com/thread/28157

**Comment by amboar** [comment]
systemd-networkd doesn't let you configure that because as @mdmillerii says it doesn't make much sense. The gateway deals with switching from layer 2 to 3 in the OSI model. To get packets off of your local network (layer 2) you need them to be routed (layer 3). The purpose of the gateway on non-router machines is to provide a target to aim packets for all packets whose destination is not on the local network. If you define your gateway as outside of the local network, then the machine has no means to forward packets outside of its network because it needs a local gateway to which to send the packets.

It may work if you also define a static route to the gateway machine in addition to defining the gateway itself, but I think systemd's behaviour is right - if you're doing this then you network setup is very unconventional.

I don't think it's worth the effort to support if we have no concrete use-case.

**Comment by ratagupt** [comment]
systemd-networkd doesn't let you configure that because as @mdmillerii says it doesn't make much sense.
        systemd-networkd allows but in a different way,We can not directly configure we will get the response saying"No route to host".

The purpose of the gateway on non-router machines is to provide a target to aim packets at for all packets whose destination is not on the local network. If you define your gateway as outside of the local network, then the machine has no means to forward packets outside of its network because it needs a local gateway to which to send the packets
       I had the same thought and that's why we didn't do in first place.Now as I pasted the above link we can configure the gateway in different subnet.

It may work if you also define a static route to the gateway machine in addition to defining the gateway itself, but I think systemd's behaviour is right
      I would say systemd-networkd allows excatly the same way how linux allows,We need to configure the static route..
     If we do the same with systemd-networkd then systemd allows to configure it..
I would paste the systemd-networkd  conf also for that.

Now here we can take a call on whether we need this or not or why should we stop user to configuring it?

**Comment by amboar** [comment]
@ratagupt FWIW, you can make nice looking quotes that are easy to read, see [Github's article on mastering markdown](https://guides.github.com/features/mastering-markdown/), particularly the Blockquotes section. You write:

```
> This is a block quote
```
and it renders like:
> This is a block quote

Anyway,

> Now here we can take a call on whether we need this or not or why should we stop user to configuring it?

Why don't we wait for someone who has this use case to come along and implement it themselves? We're not *stopping* anyone - the software is open source, anyone can modify it. If they have such a use-case they can send a patch enabling it.

**Comment by ratagupt** [comment]
> Why don't we wait for someone who has this use case to come along and implement it themselves? We're not stopping anyone - the software is open source, anyone can modify it. If they have such a use-case they can send a patch enabling it.
By opening a issue my aim was not to fix it.It should be in our radar.I don't see any harm if we implement this in future.

**Comment by amboar** [comment]
Ok, sounds good
