### ISSUE TITLE
Memory leak in phosphor-webui

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3083]
Used Chrome DevTools Performance.
Steps to recreate:
Fresh browser, no other tabs open. 
Went to the Web UI running on a Witherspoon. 
After DevTools are up, click Performance, select memory, and then record.
Logged into the Web UI. 
Then for ~1 minute navigated the different tabs in the UI (e.g. server overview, sensors, hardware) . I did not change network settings, change the password, boot the server, or upload an image or any other firmware actions.
Then Logged out. 
Stopped the recording. 
As the graphs below show we are leaking memory. 

The first image was v2.1-366-g26fcc80 but saw this on multiple systems/versions.  

![memory_leak](https://user-images.githubusercontent.com/5455127/38576802-ca82dc68-3cc4-11e8-8aea-f2b1100ede9c.PNG)

![memory_leak2](https://user-images.githubusercontent.com/5455127/38576805-cbe45c76-3cc4-11e8-91d5-d0a97cae64a8.PNG)

**Comment by gtmills** [comment]
This might be a better test.
You can manually force the garbage collection.. 
So start recording, force garbage collection, log in, ~1 minute navigated the different tabs, log out, force garbage collection, end recording. 

![memory_leak3](https://user-images.githubusercontent.com/5455127/38584509-2728716e-3cdc-11e8-88cd-0d1a8269e682.PNG)

After 1st garbage collection ~19MB. After 2nd garbage collection ~24MB.

**Comment by edtanous** [comment]
If the objects are attached to the scope, they should be destroyed when the scope is destroyed automatically.  I might suggest a slight change to your test procedure.

1. log in.
2. walk through all the UI windows.
3. Log out
4. force a garbage collection, and record the memory used.
Repeat steps 1-4 a few time and see if you get increasing numbers on step 4.

If the memory is actually increasing on step 4, you can dump a heap snapshot in chrome, and compare the two.  https://developers.google.com/web/tools/chrome-devtools/memory-problems/heap-snapshots

Just because we're using memory, doesn't necessarily mean that it was "leaked".  Angular keeps plenty of objects lying around and cached so it can start modules up faster a second time.

**Comment by gtmills** [comment]
1. Forced garbage collection. 
2. Took heap-start snapshot and started recording. 
3. Logged in
4. Navigated to every page.
5. Logged out.
6. Forced a garbage collection. 
7. Repeated steps 3-6 three more times (four total).
8. After last time through and after garbage collection ended recording and took heap end snapshot.

![heap](https://user-images.githubusercontent.com/5455127/44171714-9633f880-a0a0-11e8-9998-e19f76d1101d.PNG)
Heap grew from ~19MB to ~27MB.

**Comment by gtmills** [comment]
.heapsnapshot are not supported by GitHub issues. 
Here are screenshots:
![snapshot1](https://user-images.githubusercontent.com/5455127/44171932-3ab63a80-a0a1-11e8-9da9-44aa3bab2ee4.PNG)
![snapshot2](https://user-images.githubusercontent.com/5455127/44171935-3c7ffe00-a0a1-11e8-9ab7-186e0a81c838.PNG)
