### ISSUE TITLE
[Witherspoon]: How to use BMC dedicated port and assign BMC ip by DHCP?

### ISSUE THREAD

**Issue by ouyangxx10** [openbmc/openbmc#3085]
1. Modify witherspoon platform configuration file:
```
UBOOT_MACHINE = "ast_g5_ncsi_config" --> UBOOT_MACHINE = "ast_g5_phy_config"
```
2. Disable kernel NCSI options:
```
CONFIG_NET_NCSI=y  --> CONFIG_NET_NCSI=n
```
3. rebuild de image

But it doesn't seem to work.
```
[   31.310256] ftgmac100 1e660000.ethernet eth0: NCSI: No channel found with link
[   31.317516] ftgmac100 1e660000.ethernet eth0: NCSI interface down
```
```
root@witherspoon:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 3E:7E:CA:6A:BF:93
          inet addr:169.254.141.24  Bcast:169.254.255.255  Mask:255.255.0.0
          inet6 addr: fe80::3c7e:caff:fe6a:bf93%959/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:19

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1%959/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:146 errors:0 dropped:0 overruns:0 frame:0
          TX packets:146 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:11174 (10.9 KiB)  TX bytes:11174 (10.9 KiB)
```

**Comment by amboar** [comment]
The Witherspoon BMC doesn't have a dedicated network PHY, so I don't understand why you would make such a change and expect it to work.

**Comment by ouyangxx10** [comment]
@amboar  I want porting the witherspoon to X86 system.(BMC chips is aspeed2500).

**Comment by amboar** [comment]
@ouyangxx10 you're probably best sending mail to the list at this point rather than trying to sort it out through the issue tracker; porting OpenBMC to new systems isn't at all well documented. Witherspoon is an OpenPOWER system, not an x86 system, and so it's probably not the best starting point for what you want to do. The Quanta Q71L (an x86 machine) is in the upstream repository - you might want to base your efforts off of that instead. There are some bugs with it currently, though there are also patches in Gerrit to fix them up:

https://gerrit.openbmc-project.xyz/#/c/10126/
https://gerrit.openbmc-project.xyz/#/c/10127/

I'm going to close the issue on the expectation that you'll jump onto IRC or send mail to the list, and we can help you out from there. If you think this is unreasonable, please feel free to discuss.
