### ISSUE TITLE
Unexpected "xyz.openbmc_project.Common.Error.InternalFailure (FQPSPCR0021F) error during hot swap of Fan

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3106]
<cde:info> SW424212 </cde:info>

**Comment by amboar** [comment]
Please provide a description of the publicly accessible affected versions any context necessary to reproduce the problem.

**Comment by tomjoseph83** [comment]
This is a duplicate of issue #3016 and the summary  is that whenever FRU ID 0 (or any other unsupported  FRU ID) is passed to the net-ipmid, error is logged. Since user input is invalid, an appropriate IPMI completion code is the right response.  The change is up for review https://gerrit.openbmc-project.xyz/#/c/9804
