### ISSUE TITLE
Need ability to add new u-boot env variables during update

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#3128]
If a new u-boot environment variable is added to the image (via a u-boot update / patch), it's not updated via the regular firmware update process because the u-boot env mtd is not updated, only a full flash write would write the default to the env mtd.

Need a way for the code update process to know there are new env variables shipped with the image and manually set them to a default value if they don't exist.

**Comment by mdmillerii** [comment]
Since the default environment is compiled into the `setenv` tool, one approach is to have a config that runs the tool against an empty file which would print the default environment then look for variables that need to be added.  This would not address deletions (probably not a big issue), nor would it address needed preferred alternatives, but could be used to add missing settings.
