### ISSUE TITLE
GUI code update image upload times out intermittently

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3182]
<cde:info> SW429266 </cde:info>

**Comment by geissonator** [comment]
It was found during internal testing that the all http requests are having their timeout for their operation overridden by the code in app/common/services/apiInterceptor.js.  So in situations like uploadImage() in app/common/services/apiInterceptor.js, where a timeout larger then the default of 20s is requested, it gets overwritten.

The default was attempted to be set in app/index.js but if you read through https://tinyurl.com/yc7kayhx you'll see that it doesn't work how you expect it to.

The fix is to add a check in the interceptor that only sets the default if the caller didn't set it to something.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10618> Do not override http timeout if caller has set it
Resolves  #3182 GUI code update image upload times out intermittently
