### ISSUE TITLE
Current password rule is not enforced in GUI when changing to a new password

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3190]
<cde:info> SW429576 </cde:info>

**Comment by gtmills** [comment]
Need a change in the rest server 

EdTanous (IRC)
 that looks like a bug in the rest server, it shouldn't be checking for credentials on the login api
withCredentials in javascript can only override token based auth;  Right now the webui is using cookie based auth, with the security set so the javascript has no access to it
Looks like the bug is here: https://github.com/openbmc/phosphor-rest-server/blob/master/module/obmc/wsgi/apps/rest_dbus.py#L691
if you are already logged in, it essentially bypasses all the login checks
I suspect line 691 and 692 can just be deleted, and it should work as expected

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10648> Don't check for credentials on the login API
Resolves  #3190 Current password rule is not enforced in GUI when changing to a new password
