### ISSUE TITLE
Witherspoon: Event notification regression

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3229]
<cde:info> SW431900 </cde:info>

**Comment by amboar** [comment]
Can someone please provide an actual description of the bug and the affected publicly relevant versions?

**Comment by dkodihal** [comment]
Event notification was broken on master. It happened once we switched the webserver to nginx; nginx closes websockets after a minute of inactivity.

The right thing to do is for the webserver to implement a websocket ping. This was actually fixed by @jaypadath via https://gerrit.openbmc-project.xyz/#/c/10863/.
