### ISSUE TITLE
What approach to document security considerations for various BMC hardware?

### ISSUE THREAD

**Issue by joseph-reynolds** [openbmc/openbmc#3265]
This issue is to document a discussion from the OpenBMC security working group related to security documentation in https://gerrit.openbmc-project.xyz/#/c/11164/.  This is related to issue #3247.

The security/obmc-securityarchitecture.md document talks about what OpenBMC code does to protect itself when running on specific hardware such as ASPEED AST2500.

The question is how well this approach scales with the number of hardware models OpenBMC runs on.  For example, do we need another section for the Nuvoton W83795 series?  And another for a third manufacturer?  How do we best organize this?

General ideas were:
- OpenBMC intends to be hardware neutral (and not favor any manufacturer).
- Should we describe a minimum set of security features needed?  Ex: "You need hardware that supports this: ...."
- Use an attestation approach vs requirements?  For example, have a function validate the firmware image prior to using it boot the BMC.
- We'll probably need the security architecture descriptions for several sets of hardware before we can derive a common set of requirements.

**Comment by amboar** [comment]
> * OpenBMC intends to be hardware neutral (and not favor any manufacturer).

Right. We shouldn't favour any particular manufacturer unnecessarily, but we still need to be realistic. The userspace shouldn't really care for what hardware it's running on (with maybe some exception), but we *do* still have to provide kernel and u-boot support which *specifically* require knowledge of what machine they're running on.

As it stands OpenBMC as a project doesn't openly *recommend* ASPEED hardware, but it is what we *support*, and thus specifics are going to creep in.

Particularly around the security architecture, each SoC is going to have various and different insane hardware features that we need to address. I don't see that we have a choice other than to enumerate the supported hardware and its features, and provide strong recommendations on configuration to achieve good security.

> * Should we describe a minimum set of security features needed? Ex: "You need hardware that supports this: ...."

Maybe "We RECOMMEND hardware that supports this: ...". But it also comes back to "SHOULD NOT support" to try avoid the crazy bits where we can.

> * Use an attestation approach vs requirements? For example, have a function validate the firmware image prior to using it boot the BMC.

I think we will need both. Platforms that we currently support do not provide mechanisms for attestation, so that's not an option (leaving just requirements for these machines). If you don't have hardware attestation then I think you're pretty hosed from an integrity perspective, but we can make compromise difficult. I guess that's the job of the requirements mentioned here?

> * We'll probably need the security architecture descriptions for several sets of hardware before we can derive a common set of requirements.

Right. I don't think we'll ever achieve something common for hardware features like the ASPEED AHB bridges (apart from within the ASPEED product line), but certainly considering Nuvoton in the mix should shake out what's common and what's unique.
