### ISSUE TITLE
Lack some property in redfish

### ISSUE THREAD

**Issue by tylertengsurf** [openbmc/openbmc#3446]
I built redfish into openbmc on evb-ast2500. When I access redfish I found that some property can't be find in service root as below.
 curl -k -X GET -H "X-Auth-Token: z1OervucUQT2g6vyP4pJ" -i https://xx.xx.xx.xx/redfish/v1/
{
  "@odata.context": "/redfish/v1/$metadata#ServiceRoot.ServiceRoot",
  "@odata.id": "/redfish/v1/",
  "@odata.type": "#ServiceRoot.v1_1_1.ServiceRoot",
  "AccountService": {
    "@odata.id": "/redfish/v1/AccountService"
  },
  "Chassis": {
    "@odata.id": "/redfish/v1/Chassis"
  },
  "Id": "RootService",
  "JsonSchemas": {
    "@odata.id": "/redfish/v1/JsonSchemas"
  },
  "Links": {
    "Sessions": {
      "@odata.id": "/redfish/v1/SessionService/Sessions"
    }
  },
  "Name": "Root Service",
  "RedfishVersion": "1.1.0",
  "Registries": {
    "@odata.id": "/redfish/v1/Registries"
  },
  "SessionService": {
    "@odata.id": "/redfish/v1/UpdateService"
  },
  "Systems": {
    "@odata.id": "/redfish/v1/Systems"
  },
  "UUID": "60d56dab-7aa1-49d6-9477-819bfde85deb",
  "UpdateService": {
    "@odata.id": "/redfish/v1/UpdateService"
  }
}
curl -k -X GET -H "X-Auth-Token: z1OervucUQT2g6vyP4pJ" -i https://xx.xx.xx.xx/redfish/v1/Chassis
{
  "@odata.context": "/redfish/v1/$metadata#ChassisCollection.ChassisCollection",
  "@odata.id": "/redfish/v1/Chassis",
  "@odata.type": "#ChassisCollection.ChassisCollection",
  "Members": [],
  "Members@odata.count": 0,
  "Name": "Chassis Collection"
}
I couldn't find Tasks, Managers. etc. in service root and there is no member in chassis. Did I miss package need build in? 
I also want to find metadata or json file for redfish in openbmc. Could some one tell me where to find these file?
Is any function flow datagram or doc to understand how redfish work in openbmc? thanks.

**Comment by edtanous** [comment]
The codebase in question:
https://github.com/openbmc/bmcweb
You might look at the Developing.md document, that might lead to some documentation, although we don't tend to have flow diagrams that exist outside the code.

"I couldn't find Tasks, Managers. etc. in service root and there is no member in chassis. Did I miss package need build in?"
TaskService is not yet supported.  It is on the roadmap. If you're interested in writing support for it, I'm happy to help give direction if you need to know where to start.
Managers route was likely present, but not enumerated properly, and was fixed in commit aa7cb21191d9922f505c99e92b5746ec36dcbaa7
On the empty Chassis, we're likely missing inventory definitions for the EVB, and therefore cannot find any Chassis instances.  The two candidates for supporting that would be entity-manager or phosphor-inventory-manager.

**Comment by edtanous** [comment]
Any updates?  Can this bug be closed?

**Comment by gtmills** [comment]
@tylertengsurf Can we close?

**Comment by gtmills** [comment]
No response. Closing. Please reopen if still a problem.
Thanks! Gunnar
