### ISSUE TITLE
Changes to phosphor-fan-control yaml files are not detected

### ISSUE THREAD

**Issue by illiav** [openbmc/openbmc#3548]
### Steps to reproduce

```
git clone https://github.com/openbmc/openbmc.git
cd openbmc
export TEMPLATECONF=meta-ibm/meta-romulus/conf
. openbmc-env
bitbake obmc-phosphor-image
cd ..
``` 
```
$ git describe
2.7.0-dev-698-g83ba0e083
```
Change `zones.yaml` breaking the build:
```
echo broken > meta-ibm/meta-romulus/recipes-phosphor/fans/phosphor-fan-control-zone-config/zones.yaml
```
Try building:
```
bitbake obmc-phosphor-image
```
The build finishes without errors.

Try to clean phosphor-fan:
```
bitbake -c clean phosphor-fan
bitbake obmc-phosphor-image
```
Still no errors.

Try cleansstate:
```
bitbake -c cleansstate phosphor-fan
bitbake obmc-phosphor-image
```
The build finally fails.

**Comment by msbarth** [comment]
I believe what's happening here is:
```
bitbake obmc-phosphor-image
```
- This results in building without errors due to the state cache not showing the image needs to be rebuilt

```
bitbake -c clean phosphor-fan
bitbake obmc-phosphor-image
```
- The `-c clean` removes all output files, which the generated source from the yaml is placed in the git source dir after generation (possible issue here)

```
bitbake -c cleanstate phosphor-fan
bitbake obmc-phosphor-image
```
- Why this one works, is that the state cache is cleared forcing a re-generation from the yaml
