### ISSUE TITLE
reduce openbmc image size

### ISSUE THREAD

**Issue by pranav-shivalingaiah** [openbmc/openbmc#3582]
Hi,

We are having only 32MB of QSPI Nor flash in our custom design, when we build openbmc we are getting a "flash-evb-ast2500" image which is also of 32MB size. We are now not able to perform the image upgrade due to space crunch. We are not using the IPMI and other board management support provided by openbmc.

We would like to get your help for below items.
1. Reduce the image size.
2. The boot time is too much, please suggest which sysd services can be removed.
3. We would like to use a single filesystem and remove the current Overlay mechanism.

Please suggest .

Regards,
Pranav

**Comment by mdmillerii** [comment]
You mentioned `flash-evb-ast2500` so I assume you are starting with the aspeed 2500 evaluation board as a starting point.

Regarding item 3, the decision to use an read-write overlay over `squashfs` was to get the `xz` compression method supported by `squashfs` on medium sized blocks (64kB ?) for the overall compression ratio.  While `jffs2` and other file systems support some compression, they are compressing smaller blocks.  That said, there is no reason not to adopt the `UBI` image approach of removing the `initramfs` completely and mounting the `rwfs` on `/var` and only using `overlayfs` on `/etc`.  This would save you the size of the `initramfs` (which is a duplicated `busybox` and `glibc` packaged into the FIT image).  You need a script to mount `/etc` before `systemd` starts, and you need to make arrangements for code update to not update in place a mounted filesystem (I can discuss further if needed).  

You can reduce the image size somewhat by compressing it as a single cpio and loading it as an initrd into rootfs, however you will have to wait for the whole file system to be decompressed each boot before drivers are probed and will spend all its life taking RAM (which may or not be more constrained than your flash space), but it will be faster to access files at runtime (RAM speed instead of SPI flash read and decompression, with the page cache for keeping pages in RAM based on the memory pressure).

Regarding 3, I'm not aware of any work to make a filesystem layout for `openbmc` that `systemd` supports (such as almost all static data in `/usr` mounted before it starts or an empty but writable `/etc` that is populated from `/usr` on first boot) that doesn't use `overlayfs` except a fully writable filesystem (`ext4` or `rootfs` in RAM).

Removing features may reduce both boot time and image space, but you will have to evaluate what functions your system will require.  Trimming packages is more of a `yocto` exercise than `openbmc` but note that all python utilities are now optional.
