### ISSUE TITLE
How to add users for login terminal

### ISSUE THREAD

**Issue by chineweff** [openbmc/openbmc#3601]
I find two files:
1. conf/local.conf.sample
There is a parameter named EXTRA_USERS_PARAMS
I modified this parameter(add my useradd command behind)
but it doesn't work.

2. meta-phosphor/conf/distro/include/phosphor-defaults.inc
In this file there is a parameter named EXTRA_USERS_PARAMS_pn-obmc-phosphor-image

How can I add users without modifying the common code(phosphor-defaults.inc)?

**Comment by geissonator** [comment]
@ratagupt or @rthomaiy any directions we can point people to?

**Comment by gtmills** [comment]
@ratagupt or @rthomaiy Any suggestion here?

**Comment by rthomaiy** [comment]
EXTRA_USERS_PARAMS in meta-phosphor/conf/distro/include/phosphor-defaults.inc is to set the root password in common way instead of doing it in each & every repo of local.conf.sample file. 

But if you want to add totally new user / or override, then you can do the same through local.conf.sample.

Note: To remove security issue, password setting was done on obmc-phosphor-image, instead of the base one (basically we don't want the password to be copied in the read-only file system if any, instead it must be in the overlay, in case if it is used like that).

**Comment by rthomaiy** [comment]
Also, let us know the command you have used, can try to see why it was not working for you.
