### ISSUE TITLE
Propose and implement unit test framework

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#381]

**Comment by williamspatrick** [comment]
Look at GoogleTest / GoogleMock.
Need to understand what support is already in place in yocto (and does it matter?).

**Comment by williamspatrick** [comment]
Assign to Matt Barth.

**Comment by kc8apf** [comment]
googletest is designed to be used as a submodule within each project rather than having a shared, installed copy.  They have CMake support that make it really easy to integrate if you are using CMake.  Otherwise, they ask you follow the instructions in https://github.com/google/googletest/blob/master/googletest/README.md to add it to your build system directly.

**Comment by geissonator** [comment]
### Sprint Planning Notes

- [ ] git submodule decision/implementation

**Comment by williamspatrick** [comment]
Work completed.

**Comment by shenki** [comment]
What did we end up going with?

Did we implement a project as an example?

**Comment by williamspatrick** [comment]
Yes.  The host-ipmid package.
