### ISSUE TITLE
webui not work on zynqmp

### ISSUE THREAD

**Issue by ynt1988** [openbmc/openbmc#3832]
I am running openbmc on xilinx zynqmp. But web server is not work when i access it via https.
Via debug, webui-related issues seem to be related to 64-bit processors.
So I am confused whether OpenBMC support 64-bit processors?  If yes, what special attention should be paid to it.

**Comment by edtanous** [comment]
OpenBMC as a general rule supports 64 bit processors, but as with any multi-system coding support, it is only as useful as the testing that goes into it, and I don't believe we have any upstream 64 bit targets, so it's likely there are bugs in that regard.  Feel free to open up patchsets.

bmcweb (the web server) is run on 64 bit targets as part of its development, and we regularly fix 32 vs 64 bit bugs in code, so it seems likely that your problem is in your development setup.  If you have more details, and can push the code you're working on, please reopen with the relevant details and code, and we can discuss further, but as written, the question asked in the original thread is answered.
