### ISSUE TITLE
BIOS is unable to communicate with BMC in AST2600

### ISSUE THREAD

**Issue by vijaysai** [openbmc/openbmc#3964]
I tried compiling  for evb-ast2600  and flashed the binary, the binary booted properly, and when I see Blue screen settings of BIOS  in server Management Page, I can see  BMC information as blank, which is not the case when I use default BMC Image instead of compiled OpenBmc Image.

OpenBmc is unable to execute any commands from ipmitool such as poweroff etc, can anyone suggest  how to debug this communication issue between BIOS and BMC which uses KCS interface.

**Comment by williamspatrick** [comment]
As the issue templates specify, please do not use issues for support requests.  You're more than welcome to ask these sorts of questions on Discord.  There is even an Aspeed-channel.

The EVB is an "evaluation board".  I'm not even sure how you got this to boot up a host because it is intended as a test platform for the BMC hardware, not as a systems-management card.  But... I see these kinds of questions once in a while.  There must be something I don't understand about how people are using the EVBs.
