### ISSUE TITLE
Successfully launch openBmc using sudo qemu system arm, kill the process, and restart openbmc with Wrong Image Format for boot command Error: can't get kernel image!

### ISSUE THREAD

**Issue by yk113** [openbmc/openbmc#3976]
![cf76efd205d56ad2178148f487c8e37](https://github.com/openbmc/openbmc/assets/48592608/f2e9d2e3-4640-4209-a21e-cff0136f3563)

**Comment by williamspatrick** [comment]
You've not followed the issue template or given us any information except a screenshot. How do you expect any sort of help?

What were you doing in the QEMU session when you killed it?  We can't really help if QEMU itself is corrupting the image, but we can potentially help if there is some stray code inside the QEMU session that wrote to the wrong spot.

I'm closing this for now because there is not enough information and you haven't filled out the issue template. 

Please don't give screenshots of text. Just copy/paste the text (with markdown escapes).
