### ISSUE TITLE
why there is no information on bmcweb？

### ISSUE THREAD

**Issue by DandanXu1007** [openbmc/openbmc#3999]
Hi Team,
	I want to known why there is no information on bmcweb, when i generate the rpi-sdimg file for raspberrypi4B.
	
	version: kirstone
	
	BBLAYERS:
		./meta \
		./meta-oe \
		./meta-openembedded/meta-python \
		./meta-openembedded/meta-networking \
		./meta-openembedded/meta-filesystems \
		./meta-raspberrypi \
		./meta-phosphor \
	
	IMAGE_FEATURES:
	obmc-bmc-state-mgmt \
    obmc-bmcweb \
    obmc-chassis-mgmt \
    obmc-chassis-state-mgmt \
    obmc-dbus-monitor \
    obmc-devtools \
    obmc-fan-control \
    obmc-fan-mgmt \
    obmc-flash-mgmt \
    obmc-fru-ipmi \
    obmc-health-monitor \
    obmc-host-ctl \
    obmc-host-ipmi \
    obmc-host-state-mgmt \
    obmc-ikvm \
    obmc-inventory \
    obmc-leds \
    obmc-logging-mgmt \
    obmc-remote-logging-mgmt \
    obmc-rng \
    obmc-net-ipmi \
    obmc-sensors \
    obmc-software \
    obmc-user-mgmt \
    obmc-user-mgmt-ldap \
    ${@bb.utils.contains('DISTRO_FEATURES', 'obmc-ubi-fs', 'read-only-rootfs', '', d)} \
    ${@bb.utils.contains('DISTRO_FEATURES', 'phosphor-mmc', 'read-only-rootfs', '', d)} \
    obmc-debug-collector \
    obmc-network-mgmt \
    obmc-settings-mgmt \
    obmc-telemetry \

	Based on the above information,the obmc image is successfully created. And the bmcweb is running successfully,but there is nothing on the web.Like this:
![1](https://github.com/openbmc/openbmc/assets/33384437/dd435653-b549-46d6-9b2e-a07e1d8c0d41)

#systemctl status bmcweb
![2](https://github.com/openbmc/openbmc/assets/33384437/ec14f808-63c3-4384-b416-4f248e35ba05)

 #systemctl cat bmcweb
![3](https://github.com/openbmc/openbmc/assets/33384437/8fbd05ae-c1c2-41bf-a79c-fe07aa214585)

There are executable files for each service in the system:
![4](https://github.com/openbmc/openbmc/assets/33384437/36eadb06-bf8b-464a-b305-21e4e3394d79)

when i execute the files, got the bug like this:
![5](https://github.com/openbmc/openbmc/assets/33384437/c0a37710-691d-4e40-874b-e8af349ab072)

This problem has been bothering me for a long time. Thank you very much for your help!!!

**Comment by williamspatrick** [comment]
Please stop ignoring the issue templates.  We have them set up for a reason.

> when i execute the files, got the bug like this:

This is not a bug.  This means the service is already running.  Take a look at `systemctl status` and you should see a large number of services that were started, including the one you mentioned (`phosphor-time-manager`).

> I want to known why there is no information on bmcweb, when i generate the rpi-sdimg file for raspberrypi4B.

What information are you expecting?  A raspberrypi isn't a real BMC managing a real server; almost all of the code is written assuming that a BMC is doing BMC-things.  RaspPI has very limited utility for OpenBMC, partially because nobody has written any kind of system-like configurations for it.  There is no inventory, there are no sensors, there is no server to manage.

Likely if you want the RaspPI to "do more", you're going to have to write some code and/or configuration files to get it to do more.
