### ISSUE TITLE
Ability to write hostboot scratch registers from obmc

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#649]
For debug and testing, we need to have an interface to write the scratch registers from the openbmc.  These are set in the kernel currently so we'll need some discussion on how best to provide a debug tool that can change them.

**Comment by shenki** [comment]
I think we will write a simple kernel driver to expose the scratch registers. They can then be set from userspace with sysfs or a similar API.

**Comment by sivassrr** [comment]
Good to have tool like this. Hope it will be for internal purpose only.
BMC suppose not to manipulate HW registers as per the security.
 
Or is it fine ? because we are doing what we are planning to do it from OS, right.
Want to get better understanding.
 
Sivas R. S
E-mail: sivas.srr@in.ibm.com
 
----- Original message -----From: Joel Stanley <notifications@github.com>To: openbmc/openbmc <openbmc@noreply.github.com>Cc:Subject: Re: [openbmc/openbmc] Ability to write hostboot scratch registers from obmc (#649)Date: Mon, Oct 10, 2016 11:12 AM I think we will write a simple kernel driver to expose the scratch registers. They can then be set from userspace with sysfs or a similar API.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by williamspatrick** [comment]
These are registers in the SIO logic of the BMC. Hostboot (and Skiboot) read them for configuration reasons to know certain state about the BMC. For instance, SUART vs vUART and 'memboot' mode are selected this way. There is no security concern with these registers.

**Comment by mdmillerii** [comment]
I think we should consider the nvmem subsystem to export these _scratch_ registers.  While its designed to extract per-chip customization for the kernel there are ways to name the bits, specify them in the device tree, and provide user interface though sysfs including read and write.

**Comment by shenki** [comment]
@amboar is taking a look at this

**Comment by amboar** [comment]
Sent patches to the list: 

Cover: https://lists.ozlabs.org/pipermail/openbmc/2018-April/011361.html

Patches: http://patchwork.ozlabs.org/project/openbmc/list/?series=38550&state=%2A&archive=both

**Comment by amboar** [comment]
Hostboot can no-longer access the scratch registers as SIO is disabled.
