### ISSUE TITLE
hostwatchdog refactor

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#767]
Refactor of openbmc/skeleton/hostwatchdog/host_watchdog_obj.c to use sdbusplus and c++ 14 features.

**Comment by adamliyi** [comment]
- [ ] Spend 2-3 days study led-manager to get to know with sdbusplus
- [ ] Define an interface (yaml) for host watchdog module - prefer properties than method
- [ ] Implement the new host watchdog dbus object with the new interface (may utilize existing code)

**Comment by adamliyi** [comment]
Add the boot watchdog interface in patch: https://gerrit.openbmc-project.xyz/#/c/1370/.

**Comment by adamliyi** [comment]
Patch committed here: https://gerrit.openbmc-project.xyz/#/c/1513/

**Comment by geissonator** [comment]
This was not fully resolved, implementation still needs to be done in https://gerrit.openbmc-project.xyz/#/c/1513/

**Comment by geissonator** [comment]
Time is out on this one, need it for mfg stage 3.  Vishwa to help finish it up this sprint.

**Comment by vishwabmc** [comment]
Revised task-list

- [ ] Update `Watchdog.interface.yaml` since there is no signal being sent on timeout.
- [ ] Write command line parser. There are 3 arguments to be passed now.
- [ ] Write Timer class providing timer support using sd_event
- [ ] Write Watchdog class to use Timer class and implement the interfaces.
- [ ] Create a new systemd.target that will be called by this application
- [ ] Make changes to openpower-debug-collector to add new error definitions
- [ ] Associate openpower-debug-collector with the newly created systemd.target
- [ ] Create recipe file for this with using ENV variables
- [ ] Add Gtest cases

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4530 Commit error and exit the application on error scenarios
Fixes #767 hostwatchdog refactor
