### ISSUE TITLE
pciedetect refactor

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#770]
Refactor openbmc/skeleton/pciedetect/pcie_slot_present_obj.c to use new sdbusplus code.

**Comment by williamli80** [comment]
- [ ] Find out the yaml ( where is it? ) and generate the sdbusplus binding.
- [ ] Implement the pcie_slot_present with new binding ( such as update_fru( ) use new APIs/dbus )
- [ ] Update phosphor-host-ipmid repo

right?

**Comment by geissonator** [comment]
This is focused on updating the new inventory objects.

**Comment by williamli80** [comment]
-[ ] Creating new inventory objects to inventory manager.
-[ ] Implementing pciedetect 
-[ ] calling new sdbusplus interface to update them.
Use above created inventory objects, read gpio signal, update gpio inventory objects.

**Comment by geissonator** [comment]
@spinler to check if we even wired up Witherspoon to support this function.

**Comment by geissonator** [comment]
This will require the sdbusplus client bindings to talk with inventory manager.

**Comment by geissonator** [comment]
- interrupt driven
- Make generic inventory object that is created when a GPIO is asserted (indicates presence)
- MRW information drives this program (MRW -> service files that launch inventory object)
Talk with Matt S. and Brad for details.

**Comment by williamli80** [comment]
As we discussed, because we miss the feature of GPIO in new format, currently we do following steps:
- [ ] write a program waiting for a file descriptor with sd_event.
- [ ] When data of the file descriptor changed, we make a dbus call to update the inventory item.

(Update the common file descriptor when we get new GPIO support.)
@geissonator @bradbishop @williamspatrick
