### ISSUE TITLE
host ipmi: soft power off with watchdog timers

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#930]
Per mailing lists discussion, we need the host ipmi code in phosphor-host-ipmid/host-services.c to handle some sort of watchdog timer to ensure the host is processing the soft power off request, and if not, ensure the system is powered off.
The thought was maybe one "fast" watchdog that ensure the SMS attention is processed by the host and then a "slow" watchdog that allows the host to do it's shutdown and issue the power off.

**Comment by vishwabmc** [comment]
@geissonator Please assign this to me

**Comment by vishwabmc** [comment]
After looking into it, I don't vote for running a watchdog to ensure "SMS attention is processed" since there is no ack for that SMS_ATTN.

Post sending sms attention, probably just ONE watchdog timer could be started and that can be stopped as part of actual power off command and I need to workout the ways since we don't want to be hung waiting for watchdog timeout....

**Comment by vishwabmc** [comment]
Given that its a priority, have we started seeing hot issues with this and hence want to fix?. To me, this looks like a nice to have.

**Comment by geissonator** [comment]
The current power on/off code just does the hard shutdowns.  We want to switch it over to the soft shutdowns but we need to handle the case where the host is in a bad state, hence the reason this one is higher priority.

**Comment by vishwabmc** [comment]
Task breakdown : 

[ ]

**Comment by vishwabmc** [comment]
Should have updated this before.. So the idea is to write the own timer and then use it than reusing the watchdog timer.
