### ISSUE TITLE
Yocto toolchain should use target kernel headers for builds

### ISSUE THREAD

**Issue by amboar** [openbmc/openbmc#981]
The `mboxd` tool requires kernel headers from the target (openbmc) kernel, but these are not the headers the toolchain has access to when building userspace programs. In this case (where the necessary header isn't included in the pre-packaged headers) the only work-around is to patch the kernel header into the userspace source, which is prone to getting out of sync and breaking.

Fix Yocto so the headers from the target kernel are installed for use by the toolchain.

**Comment by kc8apf** [comment]
See the comment at the top of
http://git.yoctoproject.org/cgit.cgi/poky/plain/meta/recipes-kernel/linux-libc-headers/linux-libc-headers.inc
.

**Comment by williamspatrick** [comment]
The recommendation in that file doesn't work in this case. You can't include headers for userspace from that location because you end up with a compiler warning. (Linux/types.h has a #warning in the kernel tree).

**Comment by kc8apf** [comment]
When I look in STAGING_KERNEL_DIR
(build/tmp/work-shared/${MACHINE}/kernel-source), include/linux/types.h has
no #warning.  It does #include <uapi/linux/types.h> which will do a
#warning if __EXPORTED_HEADERS__ isn't set but include/linux/types.h does
set that on the line before the include.

**Comment by kc8apf** [comment]
Or if you really need to, in your recipe, run 'make headers_install' from
STAGING_KERNEL_DIR and have it install to a path within your recipe's work
directory.

**Comment by amboar** [comment]
> When I look in STAGING_KERNEL_DIR (build/tmp/work-shared/${MACHINE}/kernel-source), include/linux/types.h has no #warning. It does #include <uapi/linux/types.h> which will do a #warning if __EXPORTED_HEADERS__ isn't set but include/linux/types.h does set that on the line before the include.

That doesn't gel with the fact that the build breaks for me and @williamspatrick . Do you have a patch/build log demonstrating it works?

> Or if you really need to, in your recipe, run 'make headers_install' from STAGING_KERNEL_DIR and have it install to a path within your recipe's work directory.

That is a less brittle solution but feels like a hack and isn't very scalable. Why not just do it right once to accommodate all packages?

**Comment by kc8apf** [comment]
On Jan 18, 2017 6:03 PM, "Andrew Jeffery" <notifications@github.com> wrote:

When I look in STAGING_KERNEL_DIR
(build/tmp/work-shared/${MACHINE}/kernel-source),
include/linux/types.h has no #warning. It does #include
<uapi/linux/types.h> which will do a #warning if *EXPORTED_HEADERS* isn't
set but include/linux/types.h does set that on the line before the include.

That doesn't gel with the fact that the build breaks for me and
@williamspatrick <https://github.com/williamspatrick> . Do you have a
patch/build log demonstrating it works?

I don't have a project that uses kernel headers on hand. Have you looked at
other projects that have this problem? What do they do?

Or if you really need to, in your recipe, run 'make headers_install' from
STAGING_KERNEL_DIR and have it install to a path within your recipe's work
directory.

That is a less brittle solution but feels like a hack and isn't very
scalable. Why not just do it right once to accommodate all packages?

Other than upstream Yocto developers explicitly saying it's the wrong
approach in the recipe that would need to change? If nothing else, ask what
to do on the Yocto mailing list.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/openbmc/openbmc/issues/981#issuecomment-273660943>, or mute
the thread

**Comment by peteut** [comment]
You're probably looking for `make -C $KDIR prepare_modules`. This is required when you're building out of tree modules.

**Comment by mdmillerii** [comment]
I would guess this is not default because it makes the toolchain (and hence all binaries) machine specific.
