### ISSUE TITLE
Enable system booting in ISTEP mode

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#987]
Hostboot requested we allow them to boot in ISTEP mode, vs normal mode.

We would skip setting this register (or maybe set to a different value, should check with Dean) which is currently done in start_host.sh:
putcfam pu 283f 20000000 -p0;        #disable istep mode

Hostboot checks that right when it starts up to tell it what it should do.

Not sure if we need it before we move over to the actual OpenFSI implementation of the power on sequence or not.

Apparently this is new in P9.  In P8 it was done by modifying BMC scratch registers.

**Comment by williamspatrick** [comment]
It seems like from discussion with Bill Hoffa they weren't asking specifically to allow 3 different modes:

1) Normal boot.
2) Normal boot but leave hostboot in "IPL by steps" mode.
3) Cronus boot.

We already support 1,3 and don't plan to do 2.

Bill was implying that 1 was actually doing 2.  We'll need to investigate this if so because that isn't what our start_host script does.
